In [1]:
import pandas as pd
import numpy as np
import torch

In [10]:
input_path = "/data/projects/Enhancer/DNABERT_feature/Greater_CpG2/random_12K/cached_train_6-new-12w-0_200_dnaprom"
#input_sequence_path = "/data/projects/Enhancer/DNABERT_feature/Greater_CpG2/1_1" 

In [11]:
data = torch.load(input_path)

In [12]:
len(data)

24000

In [92]:
for i,j in zip(data[0].input_ids , data[0].attention_mask):
    print(i,j)

2 1
429 1
1704 1
2707 1
2621 1
2279 1
910 1
3626 1
2202 1
604 1
2404 1
1412 1
1537 1
2040 1
4052 1
3907 1
3327 1
1008 1
4017 1
3768 1
2772 1
2882 1
3324 1
996 1
3972 1
3587 1
2048 1
4084 1
4033 1
3830 1
3019 1
3869 1
3174 1
396 1
1569 1
2168 1
468 1
1858 1
3323 1
989 1
3944 1
3476 1
1601 1
2296 1
977 1
3894 1
3275 1
797 1
3173 1
392 1
1553 1
2103 1
207 1
813 1
3238 1
651 1
2591 1
2158 1
428 1
1700 1
2690 1
2556 1
2017 1
3957 1
3525 1
1799 1
3087 1
47 1
174 1
684 1
2722 1
2683 1
2526 1
1900 1
3490 1
1657 1
2519 1
1870 1
3369 1
1173 1
581 1
2309 1
1030 1
10 1
25 1
87 1
333 1
1317 1
1157 1
517 1
2053 1
5 1
5 1
5 1
5 1
6 1
10 1
25 1
88 1
339 1
1343 1
1264 1
948 1
3780 1
2819 1
3072 1
4082 1
4028 1
3812 1
2946 1
3580 1
2020 1
3971 1
3584 1
2036 1
4036 1
3843 1
3069 1
4071 1
3983 1
3630 1
2220 1
674 1
2681 1
2520 1
1874 1
3386 1
1243 1
863 1
3437 1
1448 1
1683 1
2622 1
2281 1
919 1
3662 1
2346 1
1180 1
612 1
2436 1
1537 1
2040 1
4052 1
3907 1
3326 1
1004 1
4001 1
3701 1
2504 1
1811 1
3133 1


In [13]:
all_input_ids = [item.input_ids[1:196] for item in data]

In [14]:
len(all_input_ids[0])

195

In [15]:
df = pd.DataFrame(all_input_ids)

In [16]:
df

0     1     2     3     4     5     6     7     8     9    ...   185  \
0      4005  3719  2573  2086   137   536  2130   316  1249   885  ...  2466   
1      2659  2429  1510  1930  3611  2143   365  1445  1672  2578  ...  2687   
2      1934  3628  2212   642  2556  2018  3964  3553  1910  3531  ...  2794   
3       967  3855  3118   172   674  2684  2530  1916  3555  1919  ...  1869   
4       575  2286   939  3743  2671  2478  1707  2719  2670  2476  ...  2412   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
23995  2627  2301   998  3980  3620  2178   508  2020  3971  3581  ...   494   
23996   894  3564  1954  3706  2522  1882  3418  1371  1373  1382  ...  2259   
23997  1378  1401  1496  1873  3384  1233   823  3277   808  3217  ...  3116   
23998  3968  3572  1986  3836  3044  3971  3582  2027  3997  3687  ...  3318   
23999  2455  1614  2348  1187   637  2536  1940  3652  2308  1027  ...   815   

        186   187   188   189   190   191   192   193   194  
0      1659  2525  1893  3461  1543  2061    37   133   519  
1      2541  1959  3727  2605  2215   656  2611  2239   750  
2      2970  3676  2404  1411  1535  2030  4011  3743  2671  
3      3366  1163   542  2156   417  1655  2510  1836  3236  
4      1443  1661  2535  1934  3628  2211   639  2543  1966  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
23995  1961  3734  2633  2325  1094   267  1055   111   429  
23996   829  3302   908  3617  2165   456  1810  3131   221  
23997   164   641  2551  1997  3877  3206   523  2077   101  
23998   970  3868  3171   382  1516  1956  3713  2552  2004  
23999  3247   685  2728  2707  2622  2281   920  3668  2369  

[24000 rows x 195 columns]

In [18]:
df.to_csv("/data/projects/Enhancer/New_Finetune_data_with_seqFeature-encodeFeature_raw_data/CPG2_greater/random_12K/DNABERT_feature_random12K_CpG2_greater.csv", sep=",", index=False)

In [52]:
sequence_data = pd.read_csv(input_sequence_path , sep="\t")

In [26]:
sequence_data[:1]

A_Fraction  C_Fraction  G_Fraction  T_Fraction  PurPyr_Fraction  \
0       0.185       0.305       0.235       0.275            -0.16   

   AmKe_Fraction  WeSt_Fraction      CpG1      CpG2      CpG3  
0          -0.02          -0.08  0.251256  0.348485  0.368687

In [29]:
row_tensor = torch.tensor(sequence_data[:1].values)
row_tensor

tensor([[ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
          0.3485,  0.3687]], dtype=torch.float64)

In [39]:
concatenated_tensor = torch.cat((torch.tensor(data[0].input_ids), row_tensor.squeeze(0)), dim=0)

In [40]:
concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [48]:
len(concatenated_tensor)

210

In [46]:
# Split the tensor_existing
split_point = len(torch.tensor(data[0].input_ids)) - 5
first_part, second_part = torch.tensor(data[0].input_ids[:split_point]), torch.tensor(data[0].input_ids[split_point:])

# Concatenate the tensors
new_concatenated_tensor = torch.cat([first_part, row_tensor.squeeze(0), second_part])

In [47]:
new_concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [35]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25

In [38]:
row_tensor.squeeze(0)

tensor([ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
         0.3485,  0.3687], dtype=torch.float64)

In [44]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25