In [7]:
import pandas as pd
import numpy as np
import torch

In [8]:
input_path = "/data/projects/Enhancer/Finetuned_data/CPG2_KMer_all/cached_train_6-new-12w-0_210_dnaprom"
input_sequence_path = "/data/projects/Enhancer/Finetuned_data/CPG2_KMer_all/sequence_train.tsv" 
input_train_path = "/data/projects/Enhancer/Finetuned_data/CPG2_KMer_all/train.tsv"

In [9]:
data = torch.load(input_path)
sequence_data = pd.read_csv(input_sequence_path , sep="\t")
train_data = pd.read_csv(input_train_path, sep="\t")

In [27]:
len(data)

210022

In [11]:
sequence_data.shape

(210022, 10)

In [12]:
train_data.shape

(210022, 2)

In [13]:
all_input_ids = torch.tensor([f.input_ids for f in data], dtype=torch.long)
all_attention_mask = torch.tensor([f.attention_mask for f in data], dtype=torch.long)

In [14]:
all_input_ids[0]

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25

In [15]:
torch.tensor(sequence_data[:1].values)

tensor([[ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
          0.3485,  0.3687]], dtype=torch.float64)

In [16]:
all_attention_mask

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [17]:
torch.tensor(sequence_data.values).float().size(1)

10

In [18]:
add_feature_length = len(sequence_data.columns)
add_feature_length

10

In [19]:
all_input_ids[:, -(add_feature_length+4)]

tensor([3, 3, 3,  ..., 3, 3, 3])

In [20]:
result1 = torch.cat([all_input_ids[:, :-(add_feature_length+4)], torch.tensor(sequence_data.values), all_input_ids[:, -(add_feature_length+4):-add_feature_length]], dim=1)

In [21]:
result1.shape

torch.Size([210022, 210])

In [22]:
all_attention_mask[:, -(add_feature_length+4):-3]=1
#all_attention_mask[:, -13:-3]
all_attention_mask

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])

In [23]:
for i,j in zip(result1[0] , all_attention_mask[0]):
    print(i,j)

tensor(2., dtype=torch.float64) tensor(1)
tensor(2671., dtype=torch.float64) tensor(1)
tensor(2480., dtype=torch.float64) tensor(1)
tensor(1713., dtype=torch.float64) tensor(1)
tensor(2744., dtype=torch.float64) tensor(1)
tensor(2770., dtype=torch.float64) tensor(1)
tensor(2873., dtype=torch.float64) tensor(1)
tensor(3288., dtype=torch.float64) tensor(1)
tensor(851., dtype=torch.float64) tensor(1)
tensor(3390., dtype=torch.float64) tensor(1)
tensor(1260., dtype=torch.float64) tensor(1)
tensor(932., dtype=torch.float64) tensor(1)
tensor(3716., dtype=torch.float64) tensor(1)
tensor(2561., dtype=torch.float64) tensor(1)
tensor(2039., dtype=torch.float64) tensor(1)
tensor(4046., dtype=torch.float64) tensor(1)
tensor(3881., dtype=torch.float64) tensor(1)
tensor(3223., dtype=torch.float64) tensor(1)
tensor(589., dtype=torch.float64) tensor(1)
tensor(2344., dtype=torch.float64) tensor(1)
tensor(1172., dtype=torch.float64) tensor(1)
tensor(579., dtype=torch.float64) tensor(1)
tensor(2304., dty

In [24]:
result1[0]

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [162]:
mean_val = torch.mean(result1, dim=0, keepdim=True)
std_val = torch.std(result1, dim=0, keepdim=True)

normalized_tensor = (result1 - mean_val) / std_val
normalized_tensor

tensor([[    nan,  0.5088,  0.3688,  ...,     nan,     nan,     nan],
        [    nan, -0.0645,  1.5947,  ...,     nan,     nan,     nan],
        [    nan,  0.9964, -1.2049,  ...,     nan,     nan,     nan],
        ...,
        [    nan,  0.3837, -0.1362,  ...,     nan,     nan,     nan],
        [    nan, -0.9463,  1.5748,  ...,     nan,     nan,     nan],
        [    nan, -1.2411,  0.3878,  ...,     nan,     nan,     nan]],
       dtype=torch.float64)

In [161]:
mean_val = torch.mean(result1, dim=0, keepdim=True)
std_val = torch.std(result1, dim=0, keepdim=True)

# normalized_tensor = (result1 - mean_val) / std_val
# normalized_tensor

# Create a mask where standard deviation is zero
mask_std_zero = std_val == 0

# Normalize where std is not zero
normalized_tensor = (result1 - mean_val) / torch.where(mask_std_zero, torch.ones_like(std_val), std_val)

# Assign original values to columns with std=0
normalized_tensor[:, mask_std_zero.squeeze()] = result1[:, mask_std_zero.squeeze()]
normalized_tensor

tensor([[ 2.0000,  0.5088,  0.3688,  ...,  0.0000,  0.0000,  0.0000],
        [ 2.0000, -0.0645,  1.5947,  ...,  0.0000,  0.0000,  0.0000],
        [ 2.0000,  0.9964, -1.2049,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 2.0000,  0.3837, -0.1362,  ...,  0.0000,  0.0000,  0.0000],
        [ 2.0000, -0.9463,  1.5748,  ...,  0.0000,  0.0000,  0.0000],
        [ 2.0000, -1.2411,  0.3878,  ...,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [83]:
len(all_input_ids[0])

195

In [96]:
df = pd.DataFrame(all_input_ids)

In [85]:
df

0     1     2     3     4     5     6     7     8     9    ...   185  \
0       1692  2660  2436  1540  2049  4085  4040  3858  3129   215  ...   483   
1        263  1037    40   145   568  2260   835  3327  1005  4008  ...   349   
2        501  1991  3855  3119   175   687  2733  2728  2708  2628  ...  3431   
3       2332  1122   378  1497  1880  3412  1346  1273   981  3911  ...   680   
4       3623  2189   552  2194   570  2266   860  3426  1403  1503  ...  2055   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
727413  1098   282  1113   341  1351  1296  1074   188   738  2937  ...  2328   
727414  1130   409  1624  2388  1345  1269   965  3848  3092    68  ...  2219   
727415  3933  3429  1414  1545  2072    83   317  1254   907  3613  ...   129   
727416   660  2628  2306  1017  4056  3921  3384  1235   831  3310  ...   251   
727417  3539  1854  3308   929  3704  2513  1846  3275   797  3175  ...  3870   

         186   187   188   189   190   191   192   193   194  
0       1919  3565  1958  3721  2581  2120   274  1084   226  
1       1381  1413  1544  2068    67   254  1001  3992  3665  
2       1423  1581  2214   652  2596  2177   502  1996  3873  
3       2707  2621  2279   909  3623  2189   552  2194   570  
4         13    40   147   574  2282   924  3683  2429  1510  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
727413  1106   314  1241   855  3407  1325  1190   652  2595  
727414   670  2665  2453  1607  2318  1066   154   603  2398  
727415   501  1989  3846  3083    30   107   414  1643  2461  
727416   989  3941  3464  1554  2105   216   849  3381  1224  
727417  3177   406  1609  2325  1095   271  1069   168   657  

[727418 rows x 195 columns]

In [86]:
df.to_csv("/data/projects/Enhancer/New_Finetune_data_with_seqFeature-encodeFeature_raw_data/DNABERT_feature_dataset1.csv", sep=",")

In [99]:
sequence_data

A_Fraction  C_Fraction  G_Fraction  T_Fraction  PurPyr_Fraction  \
0            0.185       0.305       0.235       0.275            -0.16   
1            0.205       0.315       0.235       0.245            -0.12   
2            0.285       0.295       0.315       0.105             0.20   
3            0.190       0.265       0.235       0.310            -0.15   
4            0.180       0.300       0.240       0.280            -0.16   
...            ...         ...         ...         ...              ...   
210017       0.185       0.275       0.260       0.280            -0.11   
210018       0.245       0.260       0.200       0.295            -0.11   
210019       0.185       0.230       0.265       0.320            -0.10   
210020       0.310       0.215       0.285       0.190             0.19   
210021       0.270       0.220       0.290       0.220             0.12   

        AmKe_Fraction  WeSt_Fraction      CpG1      CpG2      CpG3  
0               -0.02          -0.08  0.251256  0.348485  0.368687  
1                0.04          -0.10  0.271357  0.393939  0.383838  
2                0.16          -0.22  0.211055  0.398990  0.570707  
3               -0.09           0.00  0.150754  0.262626  0.328283  
4               -0.04          -0.08  0.201005  0.328283  0.393939  
...               ...            ...       ...       ...       ...  
210017          -0.08          -0.07  0.211055  0.348485  0.409091  
210018           0.01           0.08  0.180905  0.282828  0.237374  
210019          -0.17           0.01  0.140704  0.277778  0.429293  
210020           0.05           0.00  0.140704  0.252525  0.287879  
210021          -0.02          -0.02  0.160804  0.277778  0.328283  

[210022 rows x 10 columns]

In [29]:
row_tensor = torch.tensor(sequence_data[:1].values)
row_tensor

tensor([[ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
          0.3485,  0.3687]], dtype=torch.float64)

In [39]:
concatenated_tensor = torch.cat((torch.tensor(data[0].input_ids), row_tensor.squeeze(0)), dim=0)

In [40]:
concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [48]:
len(concatenated_tensor)

210

In [46]:
# Split the tensor_existing
split_point = len(torch.tensor(data[0].input_ids)) - 5
first_part, second_part = torch.tensor(data[0].input_ids[:split_point]), torch.tensor(data[0].input_ids[split_point:])

# Concatenate the tensors
new_concatenated_tensor = torch.cat([first_part, row_tensor.squeeze(0), second_part])

In [47]:
new_concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [35]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25

In [38]:
row_tensor.squeeze(0)

tensor([ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
         0.3485,  0.3687], dtype=torch.float64)

In [44]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25

In [130]:
import torch

# Example tensors
tensor1 = torch.zeros((1000, 210))
tensor1[:, -14] = 3

tensor2 = torch.rand((1000, 10))  # Some random values just for the sake of the example



# Concatenate tensors
result = torch.cat([tensor1[:, :-14], tensor2, tensor1[:, -14:]], dim=1)

print(result.shape) 


torch.Size([1000, 220])


In [131]:
result[0]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 