In [15]:
import pandas as pd
import numpy as np
import torch
import os

In [2]:
input_path = "/data/projects/Enhancer/New_Finetune_data_with_seqFeature-encodeFeature_raw_data/CPG2_greater/all/Dataset2_encode_features.csv"
#input_sequence_path = "/data/projects/Enhancer/Finetuned_data/CPG2_KMer_all/sequence_train.tsv" 

In [3]:
df= pd.read_csv(input_path, sep =",")

In [4]:
df

region  3xFLAG-AHR-HepG2_0  3xFLAG-ARID4B-HepG2_0  \
0           enhancer                   0                      0   
1           enhancer                   0                      0   
2           enhancer                   0                      0   
3           enhancer                   0                      0   
4           enhancer                   0                      0   
...              ...                 ...                    ...   
262523  non-enhancer                   0                      0   
262524  non-enhancer                   0                      0   
262525  non-enhancer                   0                      0   
262526  non-enhancer                   0                      0   
262527  non-enhancer                   0                      0   

        3xFLAG-ATF1-HepG2_0  3xFLAG-ATF1-K562_0  3xFLAG-BCL6-HepG2_0  \
0                         0                   0                    0   
1                         0                   0                    0   
2                         0                   0                    0   
3                         0                   0                    0   
4                         0                   0                    0   
...                     ...                 ...                  ...   
262523                    0                   0                    0   
262524                    0                   0                    0   
262525                    0                   0                    0   
262526                    0                   0                    0   
262527                    0                   0                    0   

        3xFLAG-CEBPA-HepG2_0  3xFLAG-CEBPG-HepG2_0  3xFLAG-CREB1-HepG2_0  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   
...                      ...                   ...                   ...   
262523                     0                     0                     0   
262524                     0                     0                     0   
262525                     0                     0                     0   
262526                     0                     0                     0   
262527                     0                     0                     0   

        3xFLAG-DMAP1-HepG2_0  ...  eGFP-ZSCAN16-HEK293_0  \
0                          0  ...                      0   
1                          0  ...                      0   
2                          0  ...                      0   
3                          0  ...                      0   
4                          0  ...                      0   
...                      ...  ...                    ...   
262523                     0  ...                      0   
262524                     0  ...                      0   
262525                     0  ...                      0   
262526                     0  ...                      0   
262527                     0  ...                      0   

        eGFP-ZSCAN18-HEK293_0  eGFP-ZSCAN21-HEK293_0  eGFP-ZSCAN23-HEK293_0  \
0                           0                      0                      0   
1                           0                      0                      0   
2                           0                      0                      0   
3                           0                      0                      0   
4                           0                      0                      0   
...                       ...                    ...                    ...   
262523                      0                      0                      0   
262524                      0                      0                      0   

In [5]:
columns_all_zero = df.columns[(df == 0).all()].tolist()

In [6]:
len(columns_all_zero)

54

In [7]:
# Calculate the percentage of zeros in each column
percentage_zeros = (df == 0).sum() / len(df) * 100

# Find columns where 90% or more rows have a value of 0
columns_90_percent_zeros = percentage_zeros[percentage_zeros >= 90].index.tolist()
columns_less_than_90_percent_zeros = percentage_zeros[percentage_zeros < 90].index.tolist()

#print(columns_90_percent_zeros)  # ['B']
print(len(columns_90_percent_zeros))  # 1
print(len(columns_less_than_90_percent_zeros)) 

3950
51


In [8]:
df[columns_less_than_90_percent_zeros]

region  H3K27me3-K562_0  H3K27me3-PC-9_0  \
0           enhancer                0                0   
1           enhancer                0                0   
2           enhancer                0                0   
3           enhancer                0                0   
4           enhancer                0                0   
...              ...              ...              ...   
262523  non-enhancer                0                0   
262524  non-enhancer                0                0   
262525  non-enhancer                0                0   
262526  non-enhancer                0                0   
262527  non-enhancer                0                0   

        H3K27me3-adrenalgland_1  H3K27me3-foreskinfibroblast_0  \
0                             0                              0   
1                             0                              0   
2                             0                              0   
3                             0                              0   
4                             0                              0   
...                         ...                            ...   
262523                        0                              0   
262524                        0                              0   
262525                        0                              0   
262526                        0                              0   
262527                        0                              0   

        H3K27me3-foreskinmelanocyte_0  H3K36me3-CD14-positivemonocyte_1  \
0                                   1                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   
...                               ...                               ...   
262523                              0                                 0   
262524                              2                                 0   
262525                              0                                 0   
262526                              0                                 0   
262527                              0                                 0   

        H3K36me3-KOPT-K1_0  H3K36me3-OCI-LY7_0  H3K36me3-UCSF-4_0  ...  \
0                        0                   0                  0  ...   
1                        0                   0                  0  ...   
2                        0                   0                  0  ...   
3                        0                   0                  0  ...   
4                        0                   0                  0  ...   
...                    ...                 ...                ...  ...   
262523                   0                   0                  0  ...   
262524                   0                   0                  0  ...   
262525                   0                   0                  0  ...   
262526                   0                   0                  0  ...   
262527                   0                   0                  0  ...   

        H3K36me3-subcutaneousabdominaladiposetissue_1  \
0                                                   0   
1                                                   0   
2                                                   0   
3                                                   0   
4                                                   0   
...                                               ...   
262523                                              0   
262524                                              0   
262525                                              0   
262526                                              0   
262527                                              0   

        H3K36me3-tibialartery_0  H3K36me3-tibiala

In [9]:
list(columns_less_than_90_percent_zeros)

['region',
 'H3K27me3-K562_0',
 'H3K27me3-PC-9_0',
 'H3K27me3-adrenalgland_1',
 'H3K27me3-foreskinfibroblast_0',
 'H3K27me3-foreskinmelanocyte_0',
 'H3K36me3-CD14-positivemonocyte_1',
 'H3K36me3-KOPT-K1_0',
 'H3K36me3-OCI-LY7_0',
 'H3K36me3-UCSF-4_0',
 'H3K36me3-ascendingaorta_0',
 'H3K36me3-bipolarneuron_0',
 'H3K36me3-brain_1',
 'H3K36me3-commonmyeloidprogenitor,CD34-positive_3',
 'H3K36me3-esophagusmuscularismucosa_0',
 'H3K36me3-esophagusmuscularismucosa_1',
 'H3K36me3-fibroblastofbreast_1',
 'H3K36me3-foreskinfibroblast_0',
 'H3K36me3-foreskinkeratinocyte_0',
 'H3K36me3-foreskinmelanocyte_0',
 'H3K36me3-gastrocnemiusmedialis_0',
 'H3K36me3-gastrocnemiusmedialis_1',
 'H3K36me3-germinalmatrix_0',
 'H3K36me3-heartleftventricle_1',
 'H3K36me3-heartleftventricle_3',
 'H3K36me3-luminalepithelialcellofmammarygland_0',
 'H3K36me3-mesenchymalstemcell_0',
 'H3K36me3-mesodermalcell_1',
 'H3K36me3-myoepithelialcellofmammarygland_0',
 'H3K36me3-neuralstemprogenitorcell_0',
 'H3K36me3-neurosphe

In [13]:
intersected_feature = pd.read_csv("/data/projects/Enhancer/New_Finetune_data_with_seqFeature-encodeFeature_raw_data/CPG2_greater/intersected_ENCODE_feature.csv", sep=",",  header=None)

In [34]:
intersected_feature[0].to_list()

['H3K27me3-foreskinfibroblast_0',
 'H3K9me3-foreskinfibroblast_0',
 'H3K9me3-foreskinkeratinocyte_0',
 'H3K27me3-K562_0',
 'H3K36me3-foreskinfibroblast_0',
 'H3K27me3-adrenalgland_1',
 'H3K27me3-foreskinmelanocyte_0',
 'H3K36me3-foreskinkeratinocyte_0',
 'H3K27me3-PC-9_0',
 'H3K36me3-peripheralbloodmononuclearcell_3',
 'H3K36me3-neurosphere_2',
 'H3K9me3-neurosphere_2',
 'H3K36me3-foreskinmelanocyte_0',
 'H3K9me3-AG04450_0',
 'H3K36me3-smallintestine_0',
 'H3K36me3-bipolarneuron_0',
 'H3K9me3-CD14-positivemonocyte_0',
 'H3K36me3-neurosphere_1',
 'H3K36me3-stomach_3',
 'H3K36me3-germinalmatrix_0',
 'H3K36me3-neuralstemprogenitorcell_0',
 'H3K36me3-neurosphere_0',
 'H3K36me3-spleen_2',
 'H3K36me3-OCI-LY7_0',
 'H3K36me3-myoepithelialcellofmammarygland_0',
 'H3K36me3-stomach_0',
 'H3K36me3-CD14-positivemonocyte_1',
 'H3K36me3-UCSF-4_0',
 'H3K36me3-tibialartery_1',
 'H3K36me3-brain_1',
 'H3K36me3-fibroblastofbreast_1',
 'H3K36me3-luminalepithelialcellofmammarygland_0',
 'H3K36me3-mesenchyma

In [65]:
folder_path = "/data/projects/Enhancer/Finetuned_data/CPG2_greater_all"
file_extension = '.tsv'
substring = 'encode'

In [66]:
def find_files_with_substring_in_name(folder_path, file_extension, substring):
    matching_files = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith(file_extension) and substring in file:
                matching_files.append(os.path.join(root, file))

    return matching_files

In [67]:
result = find_files_with_substring_in_name(folder_path, file_extension, substring)
for file_path in result:
    print(file_path)
    base_name = os.path.basename(file_path)
    name_without_extension = os.path.splitext(base_name)[0]
    new_name = name_without_extension.replace("encode", "encode_new") + os.path.splitext(file_path)[1]
    new_file_path = os.path.join(os.path.dirname(file_path), new_name)
    print(new_file_path)
    df= pd.read_csv(file_path, sep = "\t")
    print(df.shape)
    #print(df['H3K27me3-foreskinfibroblast_0'])
    df_new = df[intersected_feature[0].to_list()]
    #print(df_new)
    df_new.to_csv(new_file_path, sep="\t", index=False)

/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/encode_train.tsv
/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/encode_new_train.tsv
(210022, 4000)
/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/encode_dev.tsv
/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/encode_new_dev.tsv
(26253, 4000)
/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/Evaluation_data/encode_dev.tsv
/data/projects/Enhancer/Finetuned_data/CPG2_greater_all/Evaluation_data/encode_new_dev.tsv
(26253, 4000)


In [26]:
sequence_data[:1]

A_Fraction  C_Fraction  G_Fraction  T_Fraction  PurPyr_Fraction  \
0       0.185       0.305       0.235       0.275            -0.16   

   AmKe_Fraction  WeSt_Fraction      CpG1      CpG2      CpG3  
0          -0.02          -0.08  0.251256  0.348485  0.368687

In [29]:
row_tensor = torch.tensor(sequence_data[:1].values)
row_tensor

tensor([[ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
          0.3485,  0.3687]], dtype=torch.float64)

In [39]:
concatenated_tensor = torch.cat((torch.tensor(data[0].input_ids), row_tensor.squeeze(0)), dim=0)

In [40]:
concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [48]:
len(concatenated_tensor)

210

In [46]:
# Split the tensor_existing
split_point = len(torch.tensor(data[0].input_ids)) - 5
first_part, second_part = torch.tensor(data[0].input_ids[:split_point]), torch.tensor(data[0].input_ids[split_point:])

# Concatenate the tensors
new_concatenated_tensor = torch.cat([first_part, row_tensor.squeeze(0), second_part])

In [47]:
new_concatenated_tensor

tensor([ 2.0000e+00,  2.6710e+03,  2.4800e+03,  1.7130e+03,  2.7440e+03,
         2.7700e+03,  2.8730e+03,  3.2880e+03,  8.5100e+02,  3.3900e+03,
         1.2600e+03,  9.3200e+02,  3.7160e+03,  2.5610e+03,  2.0390e+03,
         4.0460e+03,  3.8810e+03,  3.2230e+03,  5.8900e+02,  2.3440e+03,
         1.1720e+03,  5.7900e+02,  2.3040e+03,  1.0110e+03,  4.0310e+03,
         3.8230e+03,  2.9920e+03,  3.7630e+03,  2.7510e+03,  2.7970e+03,
         2.9830e+03,  3.7270e+03,  2.6050e+03,  2.2150e+03,  6.5400e+02,
         2.6030e+03,  2.2070e+03,  6.2300e+02,  2.4770e+03,  1.7040e+03,
         2.7070e+03,  2.6220e+03,  2.2810e+03,  9.1700e+02,  3.6540e+03,
         2.3140e+03,  1.0500e+03,  9.0000e+01,  3.4600e+02,  1.3700e+03,
         1.3700e+03,  1.3720e+03,  1.3780e+03,  1.4010e+03,  1.4940e+03,
         1.8660e+03,  3.3540e+03,  1.1140e+03,  3.4600e+02,  1.3700e+03,
         1.3690e+03,  1.3680e+03,  1.3620e+03,  1.3370e+03,  1.2400e+03,
         8.4900e+02,  3.3840e+03,  1.2330e+03,  8.2

In [35]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25

In [38]:
row_tensor.squeeze(0)

tensor([ 0.1850,  0.3050,  0.2350,  0.2750, -0.1600, -0.0200, -0.0800,  0.2513,
         0.3485,  0.3687], dtype=torch.float64)

In [44]:
torch.tensor(data[0].input_ids)

tensor([   2, 2671, 2480, 1713, 2744, 2770, 2873, 3288,  851, 3390, 1260,  932,
        3716, 2561, 2039, 4046, 3881, 3223,  589, 2344, 1172,  579, 2304, 1011,
        4031, 3823, 2992, 3763, 2751, 2797, 2983, 3727, 2605, 2215,  654, 2603,
        2207,  623, 2477, 1704, 2707, 2622, 2281,  917, 3654, 2314, 1050,   90,
         346, 1370, 1370, 1372, 1378, 1401, 1494, 1866, 3354, 1114,  346, 1370,
        1369, 1368, 1362, 1337, 1240,  849, 3384, 1233,  822, 3276,  804, 3204,
         516, 2050, 4090, 4058, 3931, 3421, 1383, 1423, 1581, 2214,  652, 2594,
        2170,  473, 1880, 3411, 1343, 1261,  936, 3732, 2625, 2294,  972, 3876,
        3202,  507, 2014, 3947, 3488, 1649, 2486, 1739, 2846, 3179,  415, 1646,
        2476, 1697, 2679, 2511, 1838, 3243,  672, 2674, 2492, 1761, 2934, 3531,
        1822, 3180,  419, 1663, 2542, 1964, 3747, 2687, 2542, 1963, 3741, 2664,
        2451, 1599, 2286,  939, 3743, 2671, 2477, 1701, 2693, 2568, 2066,   60,
         227,  894, 3564, 1956, 3716, 25