In [1]:
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [2]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import pickle

In [85]:
output_file_path = "/data/private/pdutta/Wang_collaborator/clustreing_result"

In [86]:
df = pd.read_excel("/data/private/pdutta/Wang_collaborator/Survival_vs_death_first_day.xlsx")

In [87]:
df.head(50)

MouseNo  Severity  Death_0 /Survival_1          CD4         CD8a  \
0         1         1                    1   864.202653   653.388036   
1         1         1                    1   502.256482   568.373980   
2         1         1                    1   463.854773   543.952941   
3         1         1                    1  2302.596767  1930.261640   
4         1         1                    1  1058.718278  3091.961426   
5         1         1                    1  2418.428574   845.549889   
6         1         1                    1  2010.637201  2838.474841   
7         1         1                    1  1423.890754   954.820268   
8         1         1                    1  1768.039773   841.160408   
9         1         1                    1   737.596065   945.982474   
10        1         1                    1  2011.998464   936.842861   
11        1         1                    1  1064.335882  3856.099979   
12        1         1                    1  1102.194407  1086.485543   
13        1         1                    1  1015.549711   953.295367   
14        1         1                    1   749.868638  4244.576408   
15        1         1                    1  1196.291468  2161.110956   
16        1         1                    1   853.014100   893.906732   
17        1         1                    1  1872.821306  3089.504893   
18        1         1                    1  2404.970797  2655.679754   
19        1         1                    1  1717.936067  3146.932899   
20        1         1                    1   800.271331  3244.525414   
21        1         1                    1   819.176020  2848.453041   
22        1         1                    1  2861.336577  2593.128147   
23        1         1                    1  1997.352907   926.169148   
24        1         1                    1   988.257985  3647.420855   
25        1         1                    1  1137.683961  2837.144484   
26        1         1                    1  1105.987424  3249.256267   
27        1         1                    1  2482.098562  1093.547318   
28        1         1                    1  2417.559162  2612.167170   
29        1         1                    1  1123.159492  2157.111481   
30        1         1                    1  1941.685504  1389.903887   
31        1         1                    1  1659.348889  1183.768331   
32        1         1                    1  2267.904727  3362.556707   
33        1         1                    1  1794.824451  4027.166266   
34        1         1                    1  1875.930610  3058.134881   
35        1         1                    1  3161.109577  2048.802542   
36        1         1                    1  1034.560440  3951.750635   
37        1         1                    1  1234.811639  3645.199156   
38        1         1                    1  2026.824847  3082.270628   
39        1         1                    1  1214.600708  3976.365223   
40        1         1                    1  2848.713247  1309.944356   
41        1         1                    1   565.739770  1157.477863   
42        1         1                    1   958.008651  2628.535830   
43        1         1                    1   835.120535  3398.640704   
44        1         1                    1  1248.830024  2898.137821   
45        1         1                    1  2304.149343   882.254059   
46        1         1                    1   657.560865  2855.849333   
47        1         1                    1   923.432231  3484.087776   
48        1         1                    1  1044.264134  2724.021240   
49        1         1                    1  2600.124045   853.265525   

           CD25        IFN-γ       GM-CSF         IL-4         IL-5  ...  \
0    533.532407   622.283386   601.880699   523.256709   610.188377  ...   
1    988.122802   598.716245   645.511790   551.418641   560.904324  ...   
2   1117.471229  1105.009940   715.989935   541.132319   540.647678  ...   
3    588.094329  2349.30848

In [88]:
df.columns

Index(['MouseNo', 'Severity', 'Death_0 /Survival_1', 'CD4', 'CD8a', 'CD25',
       'IFN-γ', 'GM-CSF', 'IL-4', 'IL-5', 'IL-6', 'CD18', 'CD28', 'CD62L',
       'CD279', 'IL-1β', 'IL-2', 'IL-9', 'IL-10', 'TNF-α', 'CD69', 'IL-12',
       'IL-17A', 'Perforin', 'CD32', 'CD191', 'CD193', 'VEGF', 'CD11b', 'CD14',
       'CD55', 'CD183', 'CD284', 'TGF-β', 'CD66a', 'CD184', 'CD185', 'CD194',
       'CD196', 'Granzyme B', 'CCL4', 'CD15', 'CD182', 'CD197', 'IL-21',
       'HLA-DR', 'CD181', 'β-Actin', 'IL-22'],
      dtype='object')

# Clustering the entire data

In [89]:
entire_data = df.iloc[:,3:].to_numpy()
cluster_numbers = [2, 3,4, 5, 6,7,8,9,10,20, 30, 40, 50]
for i in cluster_numbers:
    print(i)
    cluster = KMeans(n_clusters=i).fit(entire_data)
    pickle.dump(cluster, open(output_file_path + '/kmeans_{}.pkl'.format(i), 'wb'))

2
3
4
5
6
7
8
9
10
20
30
40
50


In [134]:
cluster_number = 5
with open(output_file_path+'/kmeans_{}.pkl'.format(cluster_number), 'rb') as f:
    cluster_5 = pickle.load(f)

In [135]:
key_list = []
feature_list =np.zeros(cluster_number)
label_list = []
grouped_df =  df.groupby(['MouseNo'])
for key, item in grouped_df:
    #print(key)
    label_list.append(int(grouped_df.get_group(key).iloc[0]['Severity']))
    temp_df = grouped_df.get_group(key).reset_index(drop=True).iloc[:,3:].to_numpy()
    results  = cluster_5.predict(temp_df)
    #print(results)
    u, c = np.unique(results, return_counts=True)
    #print(u, c)
    feature_vec = np.zeros(cluster_number)
    for (i,j) in zip(u, c):
        feature_vec[u]= c
    #print(feature_vec)
    feature_list = np.vstack([feature_list, feature_vec])
    key_list.append(key)
feature_list = np.delete(feature_list, 0, axis=0)
print( feature_list, feature_list.shape)
print(key_list)
print(label_list)

[[134. 101. 239.  74. 107.]
 [144. 167. 149.  98. 166.]
 [ 31. 124.  60. 149. 201.]
 [  1.  32.   7.  39.  33.]
 [ 59. 200. 102. 118. 123.]
 [ 14. 113.  12. 244. 101.]
 [130. 109. 122.  71. 131.]
 [ 54. 170.  63. 142. 115.]
 [ 16. 257.  30. 248.  62.]
 [ 99.  71. 196.  82. 107.]
 [ 25. 205. 103.  87. 172.]
 [ 70. 127. 110. 124. 241.]
 [104. 105. 118.  56. 196.]
 [ 85. 151.  92. 101. 196.]
 [ 54.  94.   3. 168. 190.]
 [ 41. 197.  37.  83. 175.]
 [ 17. 107.  10. 200. 150.]
 [  5. 170.   5. 329. 144.]
 [ 39. 211.  19. 184. 271.]] (19, 5)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[1, 1, 1, 1, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4]


In [136]:
feature_list/feature_list.sum(axis=1)[:,None]

array([[0.20458015, 0.15419847, 0.3648855 , 0.1129771 , 0.16335878],
       [0.19889503, 0.23066298, 0.2058011 , 0.13535912, 0.22928177],
       [0.05486726, 0.21946903, 0.10619469, 0.26371681, 0.35575221],
       [0.00892857, 0.28571429, 0.0625    , 0.34821429, 0.29464286],
       [0.09800664, 0.33222591, 0.16943522, 0.19601329, 0.20431894],
       [0.02892562, 0.23347107, 0.02479339, 0.50413223, 0.20867769],
       [0.23090586, 0.19360568, 0.21669627, 0.12611012, 0.23268206],
       [0.09926471, 0.3125    , 0.11580882, 0.26102941, 0.21139706],
       [0.02610114, 0.41924959, 0.04893964, 0.4045677 , 0.10114192],
       [0.17837838, 0.12792793, 0.35315315, 0.14774775, 0.19279279],
       [0.04222973, 0.34628378, 0.17398649, 0.14695946, 0.29054054],
       [0.10416667, 0.1889881 , 0.16369048, 0.18452381, 0.35863095],
       [0.17962003, 0.18134715, 0.20379965, 0.09671848, 0.33851468],
       [0.136     , 0.2416    , 0.1472    , 0.1616    , 0.3136    ],
       [0.10609037, 0.18467583, 0.

In [137]:
X_train, X_test, Y_train, Y_test = train_test_split(feature_list, np.asarray(label_list), test_size=0.2, random_state=0)

In [138]:
print(X_train.shape, Y_train.shape)

(15, 5) (15,)


In [139]:
clf = RandomForestClassifier(n_estimators = 10) 

In [140]:
clf.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=10)

In [141]:
np.argsort(clf.feature_importances_)

array([2, 3, 1, 4, 0])

In [125]:
Y_pred = clf.predict(X_test)
Y_pred

array([3, 2, 3, 4])

In [126]:
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(Y_pred, Y_test))

ACCURACY OF THE MODEL:  0.5


In [127]:
print(metrics.classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         1

    accuracy                           0.50         4
   macro avg       0.38      0.50      0.42         4
weighted avg       0.38      0.50      0.42         4



/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_divisi

In [128]:
norm_features = feature_list/feature_list.sum(axis=1)[:,None]

In [129]:
X_train, X_test, Y_train, Y_test = train_test_split(norm_features , np.asarray(label_list), test_size=0.2, random_state=0)
clf1 = RandomForestClassifier(n_estimators = 100) 
clf1.fit(X_train, Y_train)

RandomForestClassifier()

In [130]:
Y_pred = clf1.predict(X_test)
Y_pred

array([3, 2, 3, 4])

In [131]:
print(metrics.classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         1

    accuracy                           0.50         4
   macro avg       0.38      0.50      0.42         4
weighted avg       0.38      0.50      0.42         4



/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/campus.stonybrook.edu/pdutta/anaconda3/envs/rapid_sampling/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_divisi